apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reg
  namespace: argocd
spec:
  description: Regression namespaces
  sourceRepos:
  - 'https://github.com/hmsvigle/*'
  destinations:
  - namespace: reg-tibco
    server: https://kubernetes.default.svc
  - namespace: reg-nodejs
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
# SyncPolicy & SyncOptions can not be set with this apiVersion