
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: hello-world
  namespace: argocd
spec: 
  destination: 
    namespace: stg
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    repoURL: "https://github.com/hmsvigle/argocd_helm.git"
    path: '/apps/'
    targetRevision: main
    helm:
      releaseName: hello-world
      valueFiles:
      - 'hello-world/values.yaml'
      - '../environments/stg-values.yaml'     
      - 'hello-world/environments/stg-values.yaml'
      parameters:
      - name: appNameGeneric
        value: 'hello-world'
      #- name: image.tag
      #  value: '01'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   