---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app-reg
  namespace: argocd
spec: 
  destination: 
    namespace: reg
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: "apps/hello-world/"
    repoURL: "https://github.com/hmsvigle/argocd_helm.git"
    targetRevision: main
    helm:
     releaseName: hello-world
     valueFiles:
     - '/apps/hello-world/values.yaml'
     - '/apps/hello-world/environments/reg-values.yaml'
     parameters:
     - name: appName
       value: "hello-world"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---      
